- id: google-style-java
  name: Google Code Style for Java
  description: Formats code in Google's Java codestyle.
  entry: google-style-format
  language: python
  types: [ java ]
  stages: [ commit, push, manual ]
